# better range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# 3 profiles (n+2)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# usb boot mode to fix kvm support
CONFIG_ZMK_USB_BOOT=y

# enable mouse
CONFIG_ZMK_MOUSE=y

# enable zmk studio
CONFIG_ZMK_STUDIO=y
